### ISSUE TITLE
List of supported "sectors" (affected verticals, victimilogy)

### ISSUE THREAD

**Issue by dr4lekhine** [eremit4/Akamaru#1]
Hi,

First of all, kudos for the tool.

Is there any list or index related to all the supported "sectors"? (for example: education, finance, defense?), etc.

Also, is there any way to "query" affected countries, motivation & attribution?. As an example, I´m showing some info of community edition of TidalCyber platform:
https://app.tidalcyber.com/groups

![image](https://github.com/eremit4/Akamaru/assets/72524642/6fe9c6e7-8abf-4eff-95d6-2194765b3757)

Thanks in advance.

Regards.

**Comment by eremit4** [comment]
Hi, @dr4lekhine! thank you for your collaboration!
Yes, I choose 12 industries that we can see in utils/utils.py.
I'll list the sectors in the README to simplify. Thank you!!
Regarding the query to filter motivations and countries involved, it is difficult because Akamaru parses the group description in MITER and Ransomware Anthology (for ransomware groups), and these descriptions are not always complete, you know?

**Comment by eremit4** [comment]
Hey, @dr4lekhine
I added the -ss flag for the user to know which sectors are supported.
Thank you!
